### PR TITLE
fix: snapzone mode parameters now work

### PR DESCRIPTION
**Pull request by vued**
### Description
Fixed highlighting of snapzones for the case that mode parameters are used.

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
With Modesexample scene

### Checklist

- [X] My code follows the [Coding Conventions](#coding-conventions)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Gusinuhe — APPROVED** [review]
Works like a charm 👍 
however when testing the `Modes Examples` scene and setting the mode as `Never`, the cube was not snapped (it just fell) but the snap condition was fulfilled when I placed the cube where the snap zone is supposed to be ⚠️

**Comment by Luphoxa** [comment]
Test Notes:
The always mode works perfectly
The never mode works perfectly
The "When near" mode works like the never mode. It does not matter if the trainee is near, the object is near or both. If this is not part of the fix then it's alright :) If it should work, maybe you can help me with setting up everything right.

Config:
Unity 2019.4.19f - Simulator
all components develop
no creator pro

**Comment by Gusinuhe** [comment]
> Test Notes:
> The always mode works perfectly
> The never mode works perfectly
> The "When near" mode works like the never mode. It does not matter if the trainee is near, the object is near or both. If this is not part of the fix then it's alright :) If it should work, maybe you can help me with setting up everything right.
> 
> Config:
> Unity 2019.4.19f - Simulator
> all components develop
> no creator pro

I think this PR works better when tested along with https://github.com/Innoactive/Creator-Examples/pull/25 and vice-versa.

**Comment by vued** [comment]
> Works like a charm 👍
> however when testing the `Modes Examples` scene and setting the mode as `Never`, the cube was not snapped (it just fell) but the snap condition was fulfilled when I placed the cube where the snap zone is supposed to be ⚠️

For me it snapped with any mode. Maybe someone else can double check this?
If this is the case, it's likely not caused by the changes made and could be reported as another bug. So I would like to continue with the merge nevertheless.

**Review by tomwim — APPROVED** [review]

**Review by SimonTheSourcerer — APPROVED** [review]

**Pull request merged**
