### PR TITLE
fix: highlight now draws all submeshes not only the first

### PR DESCRIPTION
**Pull request by Maxsiom**
### Description
The InteractableHighlighter only drew the first submesh of the mesh filter.
Now it draws all submeshes.

**Fixes**: # [TRNG-1061](https://jira.innoactive.de/browse/TRNG-1061)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Using different objects with multiple meshes (submeshes) like the winkelschrauber.fbx provided in this ticket. Then highlight it with the highlight behavior.

ezgif-4-3611073d0b20

**Test Configuration**:

### Checklist

- [x ] My code follows the [Coding Conventions](#coding-conventions)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Gusinuhe — APPROVED** [review]
Works like a charm 👌

**Comment by aleksei-korolev** [comment]
@SimonTheSourcerer doesn't this PR becomes obsolete with our tickets?

**Comment by tomwim** [comment]
> @SimonTheSourcerer doesn't this PR becomes obsolete with our tickets?

Why would it?

**Review by tomwim — APPROVED** [review]

**Review by SimonTheSourcerer — APPROVED** [review]

**Comment by SimonTheSourcerer** [comment]
It does not get obsolete, it looks perfect and should merged asap

**Review by aleksei-korolev — APPROVED** [review]

**Pull request merged**
